version: '{build}'
skip_non_tags: true
image: Visual Studio 2017
environment:
  nuget_key:
    secure: YuSNfK09e6bNa8EEC2jAsTZP8b8sHN6BDdhrqbI1hRAoqSAUUre5gH8CaW/85NpF
build_script:
- ps: |
    dotnet restore
    cd ./src/JeremyTCD.DocFx.Plugins.FileMetadataExposer
    dotnet pack -c release /p:version=$env:APPVEYOR_REPO_TAG_NAME
deploy_script:
- ps: |
    nuget setApiKey $env:nuget_key
    nuget push "./bin/release/JeremyTCD.DocFx.Plugins.FileMetadataExposer.$($env:APPVEYOR_REPO_TAG_NAME).nupkg" -Source https://www.nuget.org/api/v2/package
