version: '{build}'
branches:
  only:
  - master
skip_non_tags: true
image: Visual Studio 2017
environment:
  nuget_key:
    secure: xUmS9XKGSPKE3xAm/bvBD4St6an/7BlfLGUuIS8jPl8ofhKESLQpgXmQJ/8Cjx+C
build_script:
- ps: |
    dotnet restore
    dotnet build -c release
    cd ./src/JeremyTCD.DocFx.Plugins.FileMetadataExposer
    dotnet pack -c release --no-build /p:version=$env:APPVEYOR_REPO_TAG_NAME
    nuget setApiKey $env:nuget_key
    nuget push "./bin/release/JeremyTCD.DocFx.Plugins.FileMetadataExposer.$($env:APPVEYOR_REPO_TAG_NAME).nupkg" -Source https://www.nuget.org/api/v2/package